---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seb-guiservice
spec:
  template:
    spec:
      containers:
        - name: seb-guiservice
          env:
            - name: SEB_SERVER_PASSWORD
              $patch: delete
            - name: PROCTOR_SERVER_PASSWORD
              $patch: delete
