version: '3'
services:
  mariadb: 
    image: "mariadb:10.5"
    container_name: seb-server-mariadb
    environment:
        MYSQL_ROOT_PASSWORD: somePW
    volumes:
        - seb-server-mariadb-data:/var/lib/mysql
        - ./config/mariadb:/etc/mysql/conf.d
    ports:
        - 3306:3306
    networks:
        - ralph
    restart: unless-stopped

  seb-server:
      build:
          context: .
          args:
              - SEBSERVER_VERSION=1.5-latest
      container_name: seb-server
      environment:
          - SERVER_PORT=8080
          - SERVER_PWD=somePW
      volumes:
        - ./config:/sebserver/config
        - seb-server-logs:/sebserver/log

      ports:
          - 8080:8080
          - 9090:9090
      networks:
          - ralph
      depends_on:
          - "mariadb"
      restart: unless-stopped
            
networks:
  ralph:
  
volumes:
  seb-server-mariadb-data:
  seb-server-logs: