version: '3.5'
services:
  mariadb:
    image: "mariadb:10.5"
    container_name: seb-server-demo-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${SEBSERVER_PWD}
    ports:
      - 3306:3306
    volumes:
      - seb-server-demo-mariadb:/var/lib/mysql
      - ./config/mariadb/config.cnf:/etc/mysql/conf.d/config.cnf
    networks:
      - seb-server-network
    restart: unless-stopped

  seb-server:
    image: "anhefti/seb-server:v2.0-stable"
    container_name: seb-server
    environment:
      - JAVA_HEAP_MIN=1G
      - JAVA_HEAP_MAX=8G
      - spring_profiles_active=ws,gui,demo

      - sebserver_password=${SEBSERVER_PWD}

      # Data Base settings
      - sebserver_mariadb_password=${SEBSERVER_PWD}
      - datastore_mariadb_server_address=seb-server-demo-mariadb
      - datastore_mariadb_server_port=3306
      - spring_flyway_locations=classpath:config/sql/base,classpath:config/sql/demo

      # Set the below URL component settings from where the web-service is externally available
      # NOTE: This must be the address from that the service is externally available (not network internal address)
      - sebserver_webservice_http_external_scheme=http
      - sebserver_webservice_http_external_servername=localhost
      - sebserver_webservice_http_external_port=8080
      - sebserver_webservice_autologin_url=http://host.docker.internal

      # NOTE: Screen Proctoring settings and passwords
      - sebserver_feature_exam_seb_screenProctoring_bundled_url=http://host.docker.internal:8090
      - sps_sebserver_client_secret=${SEBSERVER_PWD}
      - sps_sebserver_password=${SEBSERVER_PWD}

    ports:
      - 8080:8080
    networks:
      - seb-server-network
    depends_on:
      - "mariadb"
    restart: unless-stopped

  sps-server:
    image: "anhefti/seb-sps:v1.0-stable"
    container_name: sps-server
    environment:
        - JAVA_HEAP_MIN=1G
        - JAVA_HEAP_MAX=6G
        - SERVER_PORT=8090
        - spring_profiles_active=prod,demo

        - sebserver_password=${SEBSERVER_PWD}

        - datastore_mariadb_server_port=3306
        - datastore_mariadb_server_address=seb-server-demo-mariadb
        - mariadb_password=${SEBSERVER_PWD}

        - sebserver_client_secret=${SEBSERVER_PWD}
        - spsgui_client_secret=${SEBSERVER_PWD}
        - sps_data_store_adapter=FULL_RDBMS
        - sps_webservice_http_external_scheme=http
        - sps_webservice_http_external_servername=localhost
        - sps_webservice_http_external_port=8090
        - sps_gui_redirect_port=3000
        - sps_init_sebserveraccount_password=${SEBSERVER_PWD}
        - spring_flyway_locations=classpath:config/sql/base,classpath:config/sql/demo
    volumes:
      - .:/sebsps/config/spring
    ports:
      - 8090:8090
    networks:
        - seb-server-network
    depends_on:
        - "mariadb"
    restart: unless-stopped

  sps-gui:
    image: naritter/seb-sps-gui:v1.0-stable
    container_name: sps-gui
    environment:
      - VITE_SERVER_URL=localhost
      - VITE_SERVER_PORT=3000
      - NODE_ENV=prod
      - SERVER_PORT=3000
      - PROCTOR_SERVER_URL=http://sps-server
      - PROCTOR_SERVER_PORT=8090
      - PROCTOR_DEFAULT_URL=/admin-api/v1
      - PROCTOR_SERVER_USERNAME=spsGuiClient
      - PROCTOR_SERVER_PASSWORD=${SEBSERVER_PWD}
      - SEB_SERVER_INTEGRATED_MODE=true
    ports:
      - 3000:3000
    networks:
      - seb-server-network
    restart: unless-stopped

networks:
  seb-server-network:
    name: seb-server-network

volumes:
  seb-server-demo-mariadb:
    name: seb-server-db