version: '3.5'
services:
  mariadb: 
    image: "mariadb:10.5"
    container_name: seb-server-mariadb
    environment:
        - MYSQL_ROOT_PASSWORD=
    volumes:
        - mariadb-data:/var/lib/mysql
        - ./mariadb:/etc/mysql/conf.d
    ports:
        - 3306:3306
    networks:
        - seb-server-network
    restart: unless-stopped

volumes:
  mariadb-data:
    name: seb-server-data
  
networks:
  seb-server-network:
    name: seb-server-network