---
apiVersion: v1
kind: Service
metadata:
  name: sps-webservice
spec:
  ports:
    - name: http
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: sps-webservice
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: sps-guiservice
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: sps-guiservice
  type: ClusterIP
