---
apiVersion: v1
kind: Service
metadata:
  name: seb-webservice
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  selector:
    app: seb-webservice
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: seb-guiservice
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  selector:
    app: seb-guiservice
